### ISSUE TITLE
우리가 지금 현재 봉착한 문제 2가지

### ISSUE THREAD

**Issue by nightmare73** [pci2676/db_pjt#11]
1. 논문에서 본 범죄데이터 분석 방법을 따와서 비슷하게 구현하려고 시도하면서 생긴 문제임. 사용한 데이터 셋 또한 비슷하게 적용하는데에서 문제가 발생함. 논문의 방법을 사용하려면 추가적으로 필요한 데이터 셋이 존재함. 이 데이터는 논문으로 따지면 poverty(가난함)과 disadventage index라는 데이터 셋인데, 이를 대체할만한 데이터를 구할 수 없음. (***논문의 disadventage 데이터는 무슨 데이터인지 알수 없어서 분석할 수 없었음)

2. 우리가 구하려고하는 최종 목표는 사망확률을 구해주는거임. 이 확률을 구하는데 있어서 신빙성을 높혀주는 작업이 논문에서 나온 방법이고 1번내용임. 하지만 그 이전에 사망률을 구할 수 있는 구체적인 데이터 셋이 존재하지 않음. 우리의 목표는 언제 어디서 죽을확률을 구하는 것인데.. (범죄율만을 보고 서술하는 것임. 교통사고 데이터는 그렇지 않음.) 언제 죽었는지에 대한 데이터셋이 없고, 어디서 죽었는지에 대한 데이터셋은 그 장소가 모호하다고 함. 결론은 범죄율에대한 지역별/일별등과 같은 세부적인 데이터 셋이 존재하지 않는다. 구체적인 데이터가 없다.

다음은 대안책임.

1. 서울시만 가지고 대상을 바꿨을 경우, (전국에서) 데이터셋이 풍부하여 가능할거라 예측됨.

**Comment by pci2676** [comment]
또 다른 대안책,
교통사고에 대한 데이터셋은 세부적인 데이터가 있으므로 교통사고로 방향을 틀어서 분석한다.

**Comment by nightmare73** [comment]
프로젝트의 진행방향을 살짝 트는 방법으로 위의 문제를 해결하였음.
지역별 소득수준에 따른 범죄 종류의 차이점을 먼저 구하고, 이전에 구하려고 했던 확률에 대해서는 전자가 해결된 다음 추가적으로 수행 하려함.
