### ISSUE TITLE
데이터셋 확보

### ISSUE THREAD

**Issue by pci2676** [pci2676/db_pjt#13]
프로젝트 진행을 위한 공공 데이터 셋 확보

**Comment by pci2676** [comment]
1. AWS S3 스토리지에 교통사고 데이터 2012년부터 2017년까지를 csv파일과 json으로 나누어 업로드 하였음.
2. 마찬가지로 각 도시별 범죄 발생 통계치또한  2014년부터 2016년까지를 csv와 json으로 나누어 업로드 하였음.

**Comment by iAmSomething** [comment]
http://kosis.kr/statisticsList/statisticsListIndex.do?menuId=M_01_01&vwcd=MT_ZTITLE&parmTabId=M_01_01&parentId=M.1;M1.2;110_11007.3;110_11007_002.4;110_11007_002_073.5;110_110_11007_002_073_1.6;#110_110_11007_002_073_1.6 
국가통계포털 / 시도군구별 세금징수실적

**Comment by pci2676** [comment]
AWS RDS 서비스에 교통사고 데이터 전부 입력했음
