### ISSUE TITLE
api 만들기

### ISSUE THREAD

**Issue by pci2676** [pci2676/db_pjt#15]

**Comment by pci2676** [comment]
api만들어야되니까 데이터 어떻게 엮을지 여기다가 적어둬

**Comment by PandaHun** [comment]
http://www.gisdeveloper.co.kr/?p=2332
행정구역 SHP

**Comment by PandaHun** [comment]
https://brunch.co.kr/@attrs/8
범죄지도 작업기

**Comment by PandaHun** [comment]
http://blog.hkwon.me/draw-korean-map-chart-with-geojson/
GeoJson 연동

**Comment by PandaHun** [comment]
https://shj7242.github.io/2018/01/16/geoInfo/
geo와 스프링

**Comment by nightmare73** [comment]
| 구하려는 수치 | 수식 |
| ------------------ | -------------------------- |
| 지역별 범죄율 | 범죄 발생건수 / 인구수 |
| 지역별 교통사고율  | 교통사고 발생건수 / 인구수 |
| 지역별 종합 사고율 | 범죄율 + 교통사고율        |
| 지역의 소득순위 | 세금 총합 / 인구수 (이 수치를 바탕으로 순위매김) |
| 지역의 범죄율 순위 | 범죄율의 순위 |

**Comment by nightmare73** [comment]
https://www.nts.go.kr/openinfo/openinfo_03_01_map.asp
지역별 고액상습체납자 명단 (공개API 지만 직접 다운로드 불가)
