### ISSUE TITLE
데이터 연관성 찾기

### ISSUE THREAD

**Issue by nightmare73** [pci2676/db_pjt#17]
현재 데이터 연관성을 찾으려고 시도하는 것들에 대해서 써주시면 감사하겠습니다.

1. 시도해본 데이터의 연관성 SPSS
2. 기대한 결과
3. 실제 결과
4. 실제 결과로부터 알 수 있는 사실 (기대한 결과와 비교했을 때도)

혹은 연관성을 맞추기위해 어떤 데이터셋에 어떤 데이터 칼럼을 추가했는 지 등 어떤식으로 데이터들을 재 가공했는지 알려주시면 감사하겠습니다.

또, 연관성을 찾기 위해 다른 수만가지 종류의 데이터셋을 추천하기위해 댓글을 달아주셔도 감사하겠습니다.

**Comment by PsPLoG** [comment]
오프라인회의로 전달
