### ISSUE TITLE
최종 보고서 관련

### ISSUE THREAD

**Issue by nightmare73** [pci2676/db_pjt#18]
최종 보고서에 어떤 식으로 쓸지 대충 틀을 잡아보았습니당
여기에 어떤것을 더 추가하면 좋을지, 어떻게 틀의 구조를 바꿀지, 어떻게 더 형식적으로 바꿀 수 있을지 자유롭게 써주면 적극 반영하겟습니당.

1. 처음에 우리가 하려했던것들
   뒤질확률 살확률 여러가지 데이터셋을 이용하여서 여러가지 확률을 구해준다 위험도나 등등

2. 봉착한 문제. 데이터셋이 없다. SPSS에서 연관성을 찾으려 했지만 연관이 될만한 양식의 데이터셋이 존재하지 않았다. 분산되있었다? 합치는건 불가능햇다. 논문에 나온방법을 사용하려햇더니 또 맞는 데이터셋이 없다. 구체적으로 어떤 데이터세을 엮으려햇는데 무엇무엇의 칼럼이 존재하지 않아서 엮는것 자체가 불가능햇다 쓰는것도 좋을듯

3. 봉착한 문제를 통해 해결방안 = 우리는 방향을 바꾸었다. 전국 범죄율에 대해서 연관성이 있는 데이터들을 모아서 의미있는 데이터를 뽑아내어 그 지역의 위험도를 계산한다.

4. 진행을 하다가 이러이러한 확률만을 계산하는 프로그램을 만들려 했으나, 허졉함을 보신 교수님의 커트로 갈아엎고 강조하신 범죄율과의 연관성을 더 깊게 연구하려한다.

5. 이제 우리가 해야할것들

6. 이러한 협업과정에서 사용한 GIT.  커밋한 과정과 봉착한 문제에 대한 이슈들을 다뤘고 그에대한 댓글. 깃을 그냥 마스터에다가 때려밖았다는것도. 커밋의 수 그래프. 하여튼 우리가 협업을 이렇게 열심히 햇다를 알려주는 글들....존나 길게쓰고싶다 ㅠㅠ

**Comment by nightmare73** [comment]
최종보고서 알파버전 업데이트됨 피드백바람

**Comment by PandaHun** [comment]
1. 서론

개발 동기는 유지된게 맞지만 프로젝트 개요는 맞지않음 초기 개요 및 동기 라고 하면 차라리 나을듯 =>근데 개요가 딱히 없다
프로젝트의 목표가 프론트까지 생각했지만 우리의 목표는 데이터의 분석 및 검증까지로 한계를 정하지 않았나 싶음

2. 본론의 1,2가 둘다 진행방법으로 같음 왜 나눈건지 모르겠음 이름을 바꿔야댐
	1.프로젝트 준비
		1. 사용할 데이터 셋
		2. 사용하는 툴
		3. 사용할 기술
	2. 프로젝트 구현
		1. 시도한 구현 
		2. 봉착한 문제
		3. 해결방안
		4. 극복한 결과
	3. 협업

3.결론은 데이터 분석의 결과들을 설명하면 될듯

**Comment by pci2676** [comment]
현재 하고있는 항목이 비어있더라구
지금 내가 모아둔 데이터를 정제해서 AWS RDS에 넣어둔 상태이고 거기서 모든 데이터를 도시를 기준으로 JOIN을 해서 하나의 csv 파일로 추출해낸 다음 그걸 다훈이하고 민석이 한테 줘서 연관성 분석을 하고있어
